apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: alpine:latest
    name: test-container
    env:  
      - name: POD_IP
        valueFrom:  
          fieldRef:
            fieldPath: status.podIP
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $POD_IP >> /cache/index.html; date >> /cache/index.html;    sleep 10;done"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi